[platformio]
default_envs = atoms3r
src_dir = Aquarium_Espresso
boards_dir = boards

[env]
platform = espressif32 @ 6.12.0
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified
build_flags =
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DAQUARIUM_M5_PORT=1
    -DAQUARIUM_ENABLE_CARDFISH=0
build_src_filter =
    +<*.cpp>
    +<m5port/*.cpp>

[env:atoms3r]
board = m5stack-atoms3r
upload_speed = 1500000
